<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        
        <NoWarn>NETSDK1187</NoWarn>

        <Deterministic>true</Deterministic>
        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <NuGetAudit>true</NuGetAudit>
        <NuGetAuditMode>all</NuGetAuditMode>
        <NuGetAuditLevel>low</NuGetAuditLevel>

        <Authors>Mert Torun</Authors>
        <Company>TH Köln</Company>
        <Copyright>© 2025 - 2026 Mert Torun</Copyright>
        <RepositoryUrl>https://github.com/FEntwumS/FEntwumS.ContainerExtension</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>
</Project>
