blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/FEntwumS/FEntwumS.ContainerExtension/blob/main/.github/SECURITY.md
    about: Read our security policy to report vulnerabilities privately.
